spring:
  devtools:
    restart:
      exclude:  public/**
      enabled:  true
  thymeleaf:
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html; charset=utf-8
    cache: false

server:
  port: 8083
